import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { Outfit } from "next/font/google"

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const outFit = Outfit({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-outFit"
});


export const metadata: Metadata = {
  title: "Ancientech Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outFit.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
